spring.application.name=lets-play

spring.data.mongodb.uri=mongodb://localhost:27017/lets-play

app.jwt.secret=super-secret-key-change-this-in-production-must-be-long-enough
app.jwt.expiration=86400000

server.port=8080
